---
# If true, remove unused dependency packages for all module states except build-dep.
# It can also be used as the only option.
update_autoremove: false

# apt_upgrade type which can be: dist, full, yes, or safe
update_upgrade_command: dist

# Update the apt cache if it is older than the cache_valid_time. This option is set in seconds.
update_cache_valid_time: 1

# The name of the specific package will be excluded from the update.
update_excluded_packages:
  - linux-image-generic
  - linux-headers-generic
  - docker.io
  - kubeadm
  - kubelet


# Ansible Role: Reboot
pre_reboot_delay: 5
post_reboot_delay: 30


# Ansible Role: APT Package Install
package_list:
  - net-tools
  - netcat
  - iftop
  - glances
  - nfs-common
  - jq
  - zip


# Ansible Role: SNAP Package Install
snap_packages_to_install:
  - name: kubectl
    classic: true
  - name: helm
    classic: true
