---
- name: Install packages and gather facts
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ package_list }}"
  register: package_installation_results

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Print package facts
  ansible.builtin.debug:
    msg: "{{ ansible_facts.packages[item] }}"
  loop: "{{ package_list }}"
  loop_control:
    label: "{{ item }}"
